In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import mode

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!mkdir /content/drive/MyDrive/K-means

mkdir: cannot create directory ‘/content/drive/MyDrive/K-means’: File exists


In [ ]:
%cd /content/drive/MyDrive/K-means

/content/drive/MyDrive/K-means


In [ ]:
!ls

'emnist-letters-test (1).csv'  'emnist-letters-train (1).csv'


In [ ]:
data_path = '/content/drive/MyDrive/K-means/emnist-letters-train (1).csv'

In [ ]:
data = pd.read_csv(data_path)
data = data.to_numpy()
print(data)

[[ 7.  0.  0. ...  0.  0.  0.]
 [16.  0.  0. ...  0.  0.  0.]
 [15.  0.  0. ...  0.  0.  0.]
 ...
 [ 6.  0.  0. ...  0.  0.  0.]
 [14.  0.  0. ...  0.  0.  0.]
 [24.  0.  0. ... nan nan nan]]


In [ ]:
data_X = data[0:500, 1:]
data_Y = data[0:500, 0]

In [ ]:
def model(data_X , data_Y , k):
  centre_cluster = data_X[np.random.choice((np.shape(data_X)[0]),k,replace = False), :]
  distances = np.zeros([np.shape(data_X)[0], k])
  least_distant = np.argmin(distances, axis = 1)
 
  for i in range(k):
     distances[:, i] = np.sqrt(((data_X - centre_cluster[i])**2).sum(axis = 1))
  least_distant = np.argmin(distances, axis = 1)

  for i in range(k):
      centre_cluster[i,:] = (data_X[least_distant == i]).mean(axis = 0)

  return least_distant,  centre_cluster

In [ ]:
k = 50
least_distant , centre_cluster = model(data_X, data_Y, k)

In [ ]:
class_ = []
for pt1 in range(k):
  cluster = data_Y[np.where(least_distant == pt1)].tolist()
  moded = mode(cluster).mode[0]
  class_.append(moded)
for i in range(np.size(class_)):
  print('cluster', i+1 ,':', class_[i])

cluster 1 : 19.0
cluster 2 : 4.0
cluster 3 : 5.0
cluster 4 : 3.0
cluster 5 : 24.0
cluster 6 : 23.0
cluster 7 : 1.0
cluster 8 : 5.0
cluster 9 : 2.0
cluster 10 : 1.0
cluster 11 : 12.0
cluster 12 : 7.0
cluster 13 : 11.0
cluster 14 : 21.0
cluster 15 : 22.0
cluster 16 : 3.0
cluster 17 : 1.0
cluster 18 : 13.0
cluster 19 : 16.0
cluster 20 : 16.0
cluster 21 : 2.0
cluster 22 : 9.0
cluster 23 : 21.0
cluster 24 : 4.0
cluster 25 : 9.0
cluster 26 : 5.0
cluster 27 : 13.0
cluster 28 : 2.0
cluster 29 : 25.0
cluster 30 : 11.0
cluster 31 : 23.0
cluster 32 : 4.0
cluster 33 : 18.0
cluster 34 : 21.0
cluster 35 : 1.0
cluster 36 : 11.0
cluster 37 : 19.0
cluster 38 : 17.0
cluster 39 : 26.0
cluster 40 : 15.0
cluster 41 : 19.0
cluster 42 : 6.0
cluster 43 : 6.0
cluster 44 : 10.0
cluster 45 : 17.0
cluster 46 : 5.0
cluster 47 : 2.0
cluster 48 : 6.0
cluster 49 : 23.0
cluster 50 : 9.0


In [ ]:
distances = np.zeros([np.shape(data_X)[0], k])
for i in range(k):
  distances[:, i] = np.sqrt(((data_X - centre_cluster[i])**2).sum(axis = 1))
least_distant = np.argmin(distances, axis = 1)

output = []
for kmeans in least_distant:
  prediction = class_[kmeans]
  output.append(prediction)

truthtable = (output == data_Y).tolist()
truthlist = truthtable.count(True)
accuracy = (truthlist)*(100/(np.shape(data_X)[0])) 
print(accuracy, "%")


40.6 %
