In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import mode

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!mkdir /content/drive/MyDrive/KNN_data

mkdir: cannot create directory ‘/content/drive/MyDrive/KNN_data’: File exists


In [ ]:
%cd /content/drive/MyDrive/KNN_data

/content/drive/MyDrive/KNN_data


In [ ]:
!pwd

/content/drive/MyDrive/KNN_data


In [ ]:
!ls

'emnist-letters-test (1).csv'  'emnist-letters-train (1).csv'


In [ ]:
train_path = '/content/drive/MyDrive/KNN_data/emnist-letters-train (1).csv'
test_path = '/content/drive/MyDrive/KNN_data/emnist-letters-test (1).csv'

In [ ]:
train = pd.read_csv(train_path)
train = train.to_numpy()
print(train)

[[ 7.  0.  0. ...  0.  0.  0.]
 [16.  0.  0. ...  0.  0.  0.]
 [15.  0.  0. ...  0.  0.  0.]
 ...
 [ 8.  0.  0. ...  0.  0.  0.]
 [11.  0.  0. ...  0.  0.  0.]
 [ 5.  0.  0. ... nan nan nan]]


In [70]:
test = pd.read_csv(test_path)
test = test.to_numpy()
test

array([[ 1,  0,  0, ...,  0,  0,  0],
       [ 1,  0,  0, ...,  0,  0,  0],
       [ 1,  0,  0, ...,  0,  0,  0],
       ...,
       [19,  0,  0, ...,  0,  0,  0],
       [19,  0,  0, ...,  0,  0,  0],
       [19,  0,  0, ...,  0,  0,  0]])

In [71]:
train_X = train[0:20000, 1:]
train_Y = train[0:20000 , 0]

In [72]:
test_X = test[0 : 1000 , 1: ]

test_Y = test[0 : 1000 , 0]

In [73]:
distance = []

In [74]:
def model(test_X , test_Y , train_X , train_Y , k):
  prediction = []
  for i in range(0 , test_X.shape[0]):
    for j in range(0, train_X.shape[0]):
      euclidean_dist =np.sqrt(np.sum((train_X[j] - test_X[i])**2))
      distance.append(euclidean_dist)
    d = list(zip(distance , train_Y.tolist()))
    df = pd.DataFrame(d , columns=['Dist_data', 'Train_Y'])
    next_list = df.sort_values(by = ['Dist_data'], axis = 0)[:k]
    next = next_list.iloc[:, 1]
    moded = mode(next).mode[0]
    prediction.append(moded)
  return prediction

In [75]:
def accuracy(label ,  f_predict):
  truthtable = (label == f_predict).astype(int)
  truthlist = truthtable.tolist()
  accuracy = (truthlist.count(1))*(100/(np.shape(f_predict)[0]))
  print(accuracy,"%")
  return accuracy

In [76]:
k = 3

In [77]:
output = model(test_X , test_Y , train_X , train_Y , k )

In [78]:
accuracy(test_Y, output)

79.9 %


79.9